name: Release
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: '8.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'ruscon'
          git config --global user.email '27970303+ruscon@users.noreply.github.com'
          git remote set-url origin https://ruscon:$GITHUB_TOKEN@github.com/ruscon/nx-semantic-release-pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install npm dependencies
        run: pnpm install --ignore-scripts

      - name: Print versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "NX version: $(npx nx --version)"

      - name: Release
        run: pnpm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
